openapi: 3.0.4
info:
  title: API Title
  version: '1.0'
servers:
  - url: http://0.0.0.0:3000
paths:
  /auth/login:
    post:
      responses:
        '200':
          description: OK
  /auth/register:
    post:
      responses:
        '200':
          description: OK
